### ISSUE TITLE
ores and gems everywhere

### ISSUE THREAD

**Issue by mannmitmaske** [BiomeBundle/BiomeBundle#100]
I am probably not the first one to say that ores like diamond gold and emerald are too high/often. and i think maybe a bit easier customization for ores etc. because at the moment it is a bit unbalanced (no really like "diamonds like 10 blocks under a normal woodland")

~some random dude called mannmitmaske ._.

**Comment by mannmitmaske** [comment]
ok looks like the server owner (I'm just a Admin) used an older version and in v6 there are much less ores (tested in sp) sooooooooooooo

**Comment by mannmitmaske** [comment]
aaaaaaaand now there are no ores etc. at all

**Comment by MCPitman** [comment]
Ore generation is vanilla as of Biome Bundle v6
