### ISSUE TITLE
[1.12.2]Stuck loading world

### ISSUE THREAD

**Issue by cowardlyDog** [BiomeBundle/BiomeBundle#101]
MC 1.12.2
Forge 1.12.2 - 14.23.1.2556
Foamfix-0.8.1-1.12-anarchy
OptiFine_1.12.2_HD_U_C6
6GB RAM Allocated

Full log: https://pastebin.com/Q153Dnun
Crash report after force closing the game: https://pastebin.com/7YLbkAKc

**Comment by delvr** [comment]
Farseek/Streams dev here - this seems to be the same as PG85/OpenTerrainGenerator/#80 and is now fixed on the Farseek side in delvr/Farseek#35.
