### ISSUE TITLE
Some mobs from other mods (as well as vanilla slimes) not spawning at all due to biome bundle.

### ISSUE THREAD

**Issue by Scytheas** [BiomeBundle/BiomeBundle#102]
Hi just an issue I've noticed. I'm  playing with the mod vampirism and for some reason while using this mod no vampires are able to spawn and they should be about as common as zombies. Also there seems to be a lack of slimes spawning in the swamps as well as underground in the caverns. I'm not sure why this is as other mobs from other mods seem to work just not for vampirism. I contacted the mod author for vampirism and he suggested I see about posting an issue here about it.

**Comment by MCPitman** [comment]
Slimes are confirmed spawning in slime chunks as per vanilla. Can you link me to the mod you are having issues with?

**Comment by MCPitman** [comment]
Not enough information here to investigate, will re-open if the OP responds.

**Comment by vardash** [comment]
Im not the OP but i can confirm, in the Swampland regions Slimes won't spawn.
There is also a Youtuber called Welsknight, where you can see in the video that no slimes are spawning in the Swampland.

Used OTG Version = 1.12.2-v6
used: Biome Bundle Version 1.12.2-v6.1
Minecraft 1.12.2
Forgeversion: 14.23.4.2727

YT-Video: https://www.youtube.com/watch?v=p9KZ4egRIPc

greetings Vardash
