### ISSUE TITLE
Water block updates on Bukkit

### ISSUE THREAD

**Issue by sharpCreep** [BiomeBundle/BiomeBundle#103]
The biome descriptors use STATIONARY_WATER as their water block, which Bukkit interprets as water(9). But the worldconfig.ini sets WaterBlock to WATER, which Bukkit interprets as flowing_water(8). This causes chunks near large bodies of water (typically oceans) to load very slowly on the client's side, even on a pre-generated map, along with heavy bandwidth usage, as the server sends out the block updates of the water settling (from WATER to STATIONARY_WATER transition). This behaviour was confirmed with WorldEdit's //distr command.

Bandwidth usage on the client side, as seen on Rainmeter: https://imgur.com/oYTzFTk

Changing WaterBlock in worldconfig.ini to STATIONARY_WATER fixes the slow load and the high bandwidth usage, but then the waterfall-like structures (1 block of water in caves or mountain sides) will take a while to update and start flowing from the source block.

**Comment by MCPitman** [comment]
Fixed in BB v6.1.
