### ISSUE TITLE
A way to prevent village spawning underneath floating islands?

### ISSUE THREAD

**Issue by crazyirishwrencher** [BiomeBundle/BiomeBundle#104]
Floating islands have an interesting effect on village generation.

![2017-11-29_23 50 25](https://user-images.githubusercontent.com/34118405/33414666-96627b62-d560-11e7-8650-8e4c8a4fb818.png)

**Comment by MCPitman** [comment]
The islands actually have village generation disabled already, but neighboring biomes can generate them and if they run into a floating island biome this happens.

There isn't really anything I can do about this.
