### ISSUE TITLE
1.12.1 bad water source blocks

### ISSUE THREAD

**Issue by croftyraider** [BiomeBundle/BiomeBundle#106]
Sometimes the world generation doesn't generate flowing water where it should. An easy to see example is using this seed: 8031370935278107419

Go to 41/710/171 and take a look - broken water block on the side of the floating islands that now performs wonderfully well.

**Comment by MCPitman** [comment]
I just went to the seed/coords and see this, all of the water blocks are flowing as normal.

![2018-01-20_17 50 18](https://user-images.githubusercontent.com/9453952/35186342-7aa64cf0-fe0a-11e7-89dd-942ae3f3d13f.png)

**Comment by croftyraider** [comment]
I still see this regularly but lately I'm wondering if isn't worldgen lag. Sometimes the world gen completes and then suddenly water/lava start flowing.
