### ISSUE TITLE
Assign the new biome changes to a different dimension?

### ISSUE THREAD

**Issue by KAfable** [BiomeBundle/BiomeBundle#109]
If I use a mod like JED or Dimensional Control to create a new dimension that's a overworld clone (using SurfaceWorldProvider), is it possible to have those changes assigned to that dimension as well?

**Comment by NeonRexodus** [comment]
Yes, just edit the level.dat file level type to be “OTG” for each dimension/world file and let the config generate for each “world”. Beware, this is currently horrifically broken in v6.1 as described here: https://github.com/BiomeBundle/BiomeBundle/issues/113

**Comment by BiomeBundle** [comment]
This is possible now with OTGs dimension features
