### ISSUE TITLE
Crash with BiomeBundle

### ISSUE THREAD

**Issue by twoworlds** [BiomeBundle/BiomeBundle#11]
I tried to start a server with BiomeBundle but got this error:

Encountered an unexpected exception
com.khorn.terraincontrol.exception.BiomeNotFoundException: Biome Autumnal Woods not found; available biomes: JungleCliffsCanyonHigh, Cold Taiga, ForestCliffsMountainEdge, Mesa Small Edge, SnowyMountains, TropicalPillars, ForestEnchantedBorder, Mesa Sandstone, RainforestTropicalMountain, Extreme Hills Jungle, JungleAncientRocks, BirchForestMountainRange, BirchForestRocky, AlpineForest, Roofed Forest M, TundraForest, UplandsEdge, TaigaHighlands, Glacier, Jungle M, AlpineConiferMountain, Mountain Range, SwamplandSmall, DesertFlats, Jungle, ForestWoodland, DesertCliffsOasis, OceanForestHighlandsBorder, DrySavanna, MesaPaintedCanyon, IcyMountains, TemperateHills, JungleCliffsVolcano, ForestGrandFir, RiverClay, RiverSavanna, Rainforest M, ForestFir, IsleRiver, Outback, DryPlainsM, DesertSmall, Ocean, DesertRed, ForestFirThicketEdge, ForestFirMountainEdge2, ForestFirMountainEdge1, ForestCliffsLowlands, RiverRocky, Savanna Plateau, High Cliffs, DioriteCliffs, Ice Plains Spikes, TemperatePlainsDarkMeadow, Mountain Peak, OceanRocksDiorite, Marsh, SnowyCanyonMid, MountainStepsGlacier, Arctic, CanyonHigh, MonumentSmall, SnowyMesaRocks, DesertLowlandsEdge, AlpsEdge, DesertCliffsOasisEdge, Orchard, DesertTropicalPlateau, RiverDiorite, SnowyMesa, MesaVerdeCanyonMid, SnowyCanyon, Extreme Hills Edge, ForestMountain, SavannaHills, Tropical Savanna Edge, Stone Beach, ForestMountainRange, OceanPlateauLow, TemperatePlainsCypresshill, ForestHighlands, CliffsSmallEdge, Birch Meadow, OceanPlateau, RockyPlains, Savanna, Sunflower Plains, Cherry Blossom Grove, SteppeHeathland, FloatingHole, Mangrove Forest, Caverns+, BirchForestHighlands, Rainforest, RiverBirchForest, RiverTropical, TemperateLowlands, Mesa Small M, Ice Mountains, Maple Woods, Mesa Plateau F, MonumentValleyFir, RainforestTropicalEdge, Mesa Sandstone M, Mesa Desert, ForestDryEdge, Mesa Plateau M, DesertTropical, RainforestTropical, ForestCliffsBorder, HighCliffsThicket, Caverns+ M, BirchForestTropical, Savanna M, Archipelago, Cold Taiga Hills, ForestCliffsMountain, Birch Forest, Extreme Hills M, DioriteCliffsPeak, OceanIslandRoofedForest, Extreme Hills+ M, DesertOasisBorder, Mesa Verde Mountain, Cold Beach, JunglePlateauLow, TaigaSmall, JungleLowlands, MonumentValley, TaigaPlateauEdge, Alpine, Mega Spruce Taiga, TaigaHills, RiverSwampland, Pumpkin Plains, AlpsMountainEdge, ForestEnderMountain, Mesa (Bryce) Edge, Rocks, JungleHills, ColdForestFirThicketEdge, DesertCanyon, RockyHills, Mesa (Bryce) Rocks, TemperatePlainsOakgrove, CliffsSmall, RiverHaunted, SnowyCliffsMountainPeak2, Flower Field, SnowyCliffsMountainPeak1, SnowyCliffsThicketMountain, ForestCliffs, FlyingForest, River, PlainsCliffM, OceanDesertIsland, HighCliffsEdge, Tropical Savanna Summit, ForestPlateauPinyon, RiverTaiga, Cold Taiga M, ColdForestFirThicket, Roofed Fungi Forest, AlpsMountainHighlands, MonumentValleyEdge, Mega Taiga Mountains, SnowyCliff, Ominous Woods, MesaVerdeCanyon, Tundra, JungleAncient, OceanRockyIslandPeak, JungleAncientMountainTall, Roofed Forest, Redwood Forest, The Void, RiverEnchantedForest, WoodlandBorder, DesertLowlandsOasis, Taiga, Bog, PlainsCliff, SnowyCanyonHigh, SnowyMesaEdge, Desert Cliffs, SwamplandBorder, TropicalPillarSmall, DesertCanyonHigh, OceanRocksM, DesertBaobabs, TundraCliffs, RockyHillsEdge, ArchipelagoMid, Coniferous Forest, SavannaEdge, Canyon, MesaCanyon, MountainSteps, IcyMountainPeak2, IcyMountainPeak1, HighCliffsSummit, FloatingEdge, CliffsSmallPlateau, CliffsSmallMountain, TemperatePlainsOakgroveBorder, JungleEdge, OceanRockyIsland, MushroomIsland, Swampland, ForestBaldCypress, OceanPlateauM, CliffsSmallPlateau3, CliffsSmallPlateau2, Snowy Cliffs, ForestPlateau, JungleSwampy, Ice Plains, Forest, JungleCliffsEdge, Desert, TemperateHillsForest, Extreme Hills, OceanIslandDesert, SnowyMountainsEdge, BirchGrove, AlpsMountainPeak, Chaparral, Mesa Plateau, Mesa Rock, ForestConiferMountain, JungleLonePeak, ForestHills, Mesa, RiverForest, Mesa Verde Forest, DesertMountain, Birch Forest M, RiverTundra, RiverDesert, DesertLowlandsOasisEdge, SnowyPlains, HighlandsPeaks, ForestWetlandM, Swampland Bushes, BirchForestTropicalIsle2, BirchForestTropicalIsle3, Mountain Peak2, Mountain Peak3, JunglePlateau, Mesa Plateau F M, DesertSmallRed, FrozenRiver, ForestFirThicket, Extreme Hills+, FloatingPlains, RiverAutumnal, Mesa Sandstone Edge, TemperatePlainsHeathland, Flower Forest, ForestMountainRangeEdge, GiantMushroomIsland, Grove, AlpineM, AlpsForest, ForestConiferSnow2, Birch Forest Hills M, CliffsSmallMountainEdge, Ocean Island, BirchGroveBorder, SavannaSmall, DesertTropicalM, RedwoodSmall, FloatingIslands, Beach, JungleCliffs, RockyMountainPeak2, DesertRedConifer, RiverSandy, RockyMountainPeak1, Mesa River, Forest M, IceWall, Caverns, AlpsMountain3, Plains, Mesa Verde, AlpsMountain1, AlpsMountain2, JungleMountainPeak, TemperatePlainsMeadowM, MonumentM, ArcticEdge, RockyMountains, TemperatePlains, CliffsSmallForest, Mesa Verde Edge, The End, CliffsSmallForest2, RainforestTropicalMountainPeak, ForestOakSmall, Savanna Plateau M, SnowyPlainsM, AlpsMountainEdge2, DesertSmallRedEdge, TaigaHighlandsPeak, ForestFirMountain, Tropical Savanna Canyon Mid, MountainStepsEdge1, MountainStepsEdge2, Tropical Savanna Canyon, ForestLarch, Dry Plains, ForestDry, OceanIslandForest, SteppeRocks, ForestPoplar, OceanForestHighlands, RiverForestConifer, RiverEnder, Deep Ocean, Monument, Mesa Sandstone Peak, DrylandsEdge1, Mesa (Bryce) Forest, TropicalPillarLarge, Caverns Edge, ForestConiferSnow, Taiga M, DrylandsEdge2, RockyHillsCliff, Desert Cliffs Edge, Rainforest Plateau M, ForestEnchantedCaves, ForestEnderValley, ForestPlateauRoofed, SnowyCliffM, RockyPlainsM, TemperateLowlandsEdge, Mega Taiga, ForestPeak, TemperatePlainsMeadowBorder, Birch Forest Hills, GlacierM, TemperateHillsBorder, TaigaPlateau, Tropical Savanna Canyon High, JungleCliffsCanyonMid, OceanForestIsland, DesertTropicalEdge, CanyonMid, ArchipelagoHigh, BirchForestMountain, SnowyExtremeHills, SnowyLonePeak, MushroomIslandShore, Redwood Taiga Hills M, MesaVerdeCanyonHigh, MesaPeak, SnowyMesaForest, Forest Wetland, Cold Plains, FrozenOcean, Mega Taiga Hills, ForestConiferEdge, SnowyCliffsEdge, BirchForestTropicalIsle, JungleCliffsCanyon, DesertLowlands, RockyPlainsSmall, TemperatePlainsM, AlpsMountainPeak2, ColdTaigaBorder, ForestPinyon, DioriteCliffsM, Webbed Hills, SnowyCliffsThicket, RedMountain, TundraEdge, RiverVerde, TropicalMountain, TemperateLonePeak, RiverAlpine, Hell, Desert M, AlpineConiferSnow, JungleMountainRange, RiverRoofedForest, SwamplandLarge, Alps, Mesa Small, HighCliffsThicketMountain, MountainStepsGlacierEdge2, MarshBorder, UplandsBlackSpruce, Caverns M, Mesa (Bryce), Swampland M, Grassland, ForestEnchantedGrove, RiverWetland, Rainforest Plateau Low, Webbed Forest Grove, JungleAncientMushrooms, Cold Desert, Drylands, ForestBaldCypressSmall, Beach Desert, OceanRocks, JungleAncientMountain, MountainStepsGlacierEdge1, DesertOasis, JungleEdge M, RainforestBog, DesertCanyonMid, Extreme Hills Jungle Edge, ForestGrandFirSmall, Webbed Hills Edge, JungleHighlands, SteppeHill, DesertHills, Rainforest Plateau, RockyMountainsPeakEdge, TemperatePlainsMeadow, DrylandsIsle, SwamplandRuins

I tried installing this mod in a normal client, started a new world but I got the same error as on my server.

**Comment by Zephyrrus** [comment]
I have the same issue on a new server

**Comment by BiomeBundle** [comment]
This is a Biome ID conflict. Open the Worldconfig.ini in the Terrain
Control folder in config. There is a list of ID numbers at the top, you
will notice there are a lot of gaps. Either change the Biome ID's here of
the Biome Bundle biomes to not clash with other mods, or configure the
other mods' biome IDs not to clash with bbundle. Do not use IDs greater
than 255.

**Comment by twoworlds** [comment]
Ok, I checked this, seems to be a problem with Biomes O Pleny installed on the same server. I removed it and the world is generated without a problem!
