### ISSUE TITLE
Giant Oceans Tiny Lands

### ISSUE THREAD

**Issue by CacheTellsStories** [BiomeBundle/BiomeBundle#116]
The title says it all. The oceans are huge while the land is limited to one singular mountainous island. Help please.

**Comment by budgej** [comment]
[An example from my custom pack.](https://imgur.com/a/cHhUm)

**Comment by MCPitman** [comment]
Sounds like you guys just spawned in the middle of an ocean, try a different seed if that's not what you want.

Here is what BB land generation looks like on a larger scale: https://i.imgur.com/XHoNm0V.jpg
