### ISSUE TITLE
Game save data in the mods folder?

### ISSUE THREAD

**Issue by jc2xs** [BiomeBundle/BiomeBundle#121]
Working on a new lighter custom pack for the EOD team.  I ran across this issue where either Biome Bundle or OTG is generating game save data under the mods folder.  In the image below I created the game "Biome Bundle Testing."  As you can see from the image it created a directory under mods\OpenTerrainGenerator for the game save as well as the normal save location.

Versions:
Forge: 14.23.1.2582
Biome Bundle v6.1
OTG v4

![capture](https://user-images.githubusercontent.com/6344780/34469215-09928032-eee8-11e7-808e-44282b4251ec.PNG)

**Comment by MCPitman** [comment]
The files in the mods folder are not game save data, they are OTG config files for the biomes and bo3s.
