### ISSUE TITLE
[LATEST] No polar bear on Polar / Ice region 

### ISSUE THREAD

**Issue by SkillzGamingYT** [BiomeBundle/BiomeBundle#123]
There isn't any Polar pear in any Ice / Snow / Polar like Biome. Such as Ice Plains biome.

**Comment by MCPitman** [comment]
I took a look at this and the spawn values for polar bears are the same as vanilla Ice Plains however they do seem to be very rare.

I'll take a look at increasing their spawn rates in the next release.

**Comment by MCPitman** [comment]
Not reported by anyone else, tested and spawn rates seem fine.
