### ISSUE TITLE
Locate Command completely break

### ISSUE THREAD

**Issue by SkillzGamingYT** [BiomeBundle/BiomeBundle#124]
/locate "something" will give out false XYZ. Village, Temple, etc...

**Comment by MCPitman** [comment]
/locate works in single player/forge.

Are you using Spigot? Is the BBundle world generated via multiverse?

**Comment by SkillzGamingYT** [comment]
No, i'm not using spigot. I'm using Forge.

What forge version are you using?

**Comment by MCPitman** [comment]
This has not been reported by anyone else and I cannot reproduce it so I'm closing this for now.
