### ISSUE TITLE
Improved Rivers Causing Chunk Errors

### ISSUE THREAD

**Issue by bonnyvonscotty** [BiomeBundle/BiomeBundle#125]
I believe I've found the problem. Using no world generation changing mods besides OTG and Biome Bundle, I found rivers with glitched edges down to bedrock, filled with water. Turning off the improved rivers in the worldconfig file solved it. The first screenshot is with improved rivers, the second is without. Nothing else has changed. https://imgur.com/a/klUNA

**Comment by MCPitman** [comment]
See my reply here: https://www.reddit.com/r/biomebundle/comments/7qxjaa/missing_chunks_filled_with_water/
