### ISSUE TITLE
Biome Specific Flora not Growing

### ISSUE THREAD

**Issue by itsbentheboy** [BiomeBundle/BiomeBundle#127]
it appears that no biome produces: 
allium, oxe-eye daisy, and azure bluet in this biome pack.

Also, biomes that should produce unique flowers when bonemeal is applied only produce: grass, dandelion, and poppy (as though using bonemeal on a grassland).

Looking to find out why specific flower types are not appearing.

**Comment by itsbentheboy** [comment]
Also possibly related: 

Ocean monuments that spawn occur with guardians in them. However, guardians do not respawn in ocean monument areas.

I will be testing this after updating some spawn settings in the future, so i am unsure if it is related, but thought i'd include this as well in case they point to a common issue.

**Comment by BiomeBundle** [comment]
Don't think this was ever verified, reopen if it's still an issue
