### ISSUE TITLE
Missing "ReplaceToBiomeName" for a lot of biomes

### ISSUE THREAD

**Issue by dskw** [BiomeBundle/BiomeBundle#129]
Hi,

I'm working on a modpack with BiomeBundle, Twilight, NetherEx and Badlands, so a lot of addional biomes next to the bundle.
After running into OTG errors about biome ID conflics I found out I had to modify my WorldConfig.ini to move all biomes behind ID 167.
This solved all conflicts with other mods, but then OTG complained about missing ReplaceToBiomeName configs for some biomes and it seems a bunch of the biome files are missing the information.

EDIT: removed the unnecessary long list as it did not contain filenames.

**Comment by dskw** [comment]
OK even after updating all the files to add proper replacement biome names it crashes:
```
[B#355]  java.lang.RuntimeException: Could not allocate the requested id 302 for biome TundraForest. All available id's under 256 have been allocated
[B#355]  . To proceed, adjust your WorldConfig or use the ReplaceToBiomeName feature to make the biome virtual.
[B#355]  	at com.pg85.otg.forge.ForgeWorld.createBiomeFor(ForgeWorld.java:210) ~[ForgeWorld.class:?]
```

I have no clue what to do about this and just suspect that the bundle really has too many biomes added to it.
I really would like to use it for my pack since I love the design of the biomes and the generated structures, but this makes it unplayable for me and I'm out of ideas how to fix it.

Any help is greatly appreciated!

**Comment by MCPitman** [comment]
This is caused by your changing of the IDs, biomes which were previously >256 that you have changed to <256 will cause errors as they are expecting a virtual biome ID (>256).

If you need to change the IDs around, keep biomes that are <256 under 256, and those that are over it >256 and you will not get this error.
