### ISSUE TITLE
Biomes which register custom IDs have no Forge Biome Dictionary support

### ISSUE THREAD

**Issue by MCPitman** [BiomeBundle/BiomeBundle#13]
This is an issue with Terrain Control which I have reported here:

https://github.com/MCTCP/TerrainControl/issues/500

The workaround to fix this in Biome Bundle without the Terrain Control devs adding support would require the removal of all custom foliage colours and mob spawning rules to have every biome register as vanilla with replacetobiomename set to a vanilla biome ID, which I REALLY do not want to do.

The real fix would be for someone to add support for the Forge Biomedict to Terrain Control, hopefully the TC devs or another code contributor will fix this for 1.10.2.

**Comment by BiomeBundle** [comment]
A new version of Biome Bundle can be downloaded from Curse ([Forge](https://minecraft.curseforge.com/projects/biome-bundle)) or Github ([Bukkit](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0)). I expect this version to fix the issue you are experiencing, a brief changelog can be found [here](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0).

Biome Bundle is now dependant on [Open Terrain Generator](https://minecraft.curseforge.com/projects/open-terrain-generator) and the installation process has changed; head over to the [installation instructions](https://github.com/BiomeBundle/BiomeBundle/wiki/Installation-Instructions) that detail how to install Biome Bundle.

Please bear in mind you will need to generate a new world with the latest update as it is not compatible with old worlds. 

Happy Exploring! ☻
