### ISSUE TITLE
Feature Request: Force spawn on land

### ISSUE THREAD

**Issue by darchitectlp** [BiomeBundle/BiomeBundle#132]
In love with this biome collection, but I'm constantly spawning in the middle of the ocean. Is it possible to add an option to force your spawn point to land so I'm not swimming for 5 minutes? Or do I need to post this at OTG?

**Comment by MCPitman** [comment]
It is on the list: https://github.com/PG85/OpenTerrainGenerator/issues/136

**Comment by BiomeBundle** [comment]
Features have been added to OTG to make land spawns more likely
