### ISSUE TITLE
Issues with Biome Bundle and Mouse Controls

### ISSUE THREAD

**Issue by Finn-Duh-Human** [BiomeBundle/BiomeBundle#135]
I've tried other packs with Open Terrain Generator, and was quite looking forward to give Biome Bundle a try, unfortunately it appears that upon moving the mouse around during game play, the mouse will jolt around crazily and randomly, despite my cpu and my in game frames not being overloaded, in other words I can move around just fine and smoothly as one would expect, but for some reason Biome Bundle is messing up the mouses sensitivity/accuracy and I don't know why.

**Comment by MCPitman** [comment]
That is not possible, Biome Bundle does nothing to affect user inputs in any way.

I would look at other causes as this is not at all possible it is caused by Biome Bundle or OTG.
