### ISSUE TITLE
[Request] Add Dynamic Trees compatibility

### ISSUE THREAD

**Issue by xieve** [BiomeBundle/BiomeBundle#136]
I was really looking forawrd to playing in a beautifully realistic world, when suddenly I noticed that most trees (not all of them, weirdly enough) were out of vanilla logs and leaves and not "dynamic" at all! So I looked into both mod's documentation, bc I thought that it couldn't be all that hard. Turns out it's not that easy, because Dynamic Trees [uses a really neat and well-functioning but obviously non-vanilla tree generation](https://github.com/ferreusveritas/DynamicTrees/wiki/World-generation). At least it's well-documented, I'd say. Soo all that's there to do is replace the biome bundle tree generation with the dynamic one when both mods are present, which isn't as easy that someone like me who's never touched java before could do it, but I believe it can't be that hard for people who programmed a mod as great as this one.

**Comment by MCPitman** [comment]
I have no plans to add this, as it's too much work.
