### ISSUE TITLE
No trees from other mods generate

### ISSUE THREAD

**Issue by Andyghandi** [BiomeBundle/BiomeBundle#137]
Have explored my new world for a while and I cant seem to find trees from other mods generate. Not from rustic, forestry etc. Is this a known problem? Some structures do generate, but I cant step upon a roguelike dungeon either. Biomes o' plenty works better with the generation of things added by other mods. Is there anything I can do to make this happen in a Biome Bundle world gen?

**Comment by BiomeBundle** [comment]
Fixed on OTGs side
