### ISSUE TITLE
Ocean biome generation bug

### ISSUE THREAD

**Issue by Davastating** [BiomeBundle/BiomeBundle#138]
I'm in the Ocean biome but it is the standard Minecraft **LAND**.
![2018-05-03_20 21 59](https://user-images.githubusercontent.com/38959343/39595413-bb46200e-4f0f-11e8-9153-1dcf984a449b.png)
The surface height (y) seems to be 90, maybe thats the problem?
![2018-05-03_20 42 36](https://user-images.githubusercontent.com/38959343/39596438-a2f7e002-4f12-11e8-8d6a-40df25f8ad27.png)

**Comment by BiomeBundle** [comment]
Was never confirmed, can't reproduce this.
