### ISSUE TITLE
1.13 support.

### ISSUE THREAD

**Issue by mibby** [BiomeBundle/BiomeBundle#147]
MC 1.13 seems to be right around the corner and Spigot has begun releasing pre-release builds for it.
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-pre7-development-builds.328883/

Do you have plans on updating BiomeBundle with any 1.13 biomes and vanilla generator changes?

**Comment by MCPitman** [comment]
Closing this as it's not the place to nag about 1.13 updates, it's an issue/bug tracker.
