### ISSUE TITLE
Every New Biome Bundle World is the same

### ISSUE THREAD

**Issue by ItzKarlPvP** [BiomeBundle/BiomeBundle#152]
Every world I try to create with biome bundle is exactly the same one . Whatever i call it , whatever i do , it generates me only 1 single world . Help?

**Comment by Mikimoka** [comment]
You probable missing seed name.... it can be changed somewhere in configs but i do recommend third party plugin multiverse plugin then you can just simple mv create <worldname> <normal is for normal world but it can be nether etc) -s <yourseednumber> -g <generatorname> for example:
mv create worldname normal -s 134314 -g OpenTerrainGenerator
