### ISSUE TITLE
Twilight Forest biomes generate in the overworld with biome bundle

### ISSUE THREAD

**Issue by Qohelethh** [BiomeBundle/BiomeBundle#154]
Certain BiomeBundle biomes appear on F3 and visually as Twilight Forest biomes. Is there a workaround for this? I am on the latest versions of OTG, Twilight Forest, etc.

**Comment by MokahTGS** [comment]
This is also an issue with Galacticcraft mobs showing up in the overworld.  There is a biome ID conflict.  How is this fixed?
