### ISSUE TITLE
World crashes when attempting to load forest biome(s)

### ISSUE THREAD

**Issue by plumprumps** [BiomeBundle/BiomeBundle#155]
Tried with and without mods. Problem persists through all 10+ test worlds. When specific forest biomes attempt to load the game crashes. **[Here is the latest crash log](https://pastebin.com/mkPNSNyn)**.

I cannot open the debug menu long enough to view which biomes cause the issue. Looks like an oak forest, large custom oak trees. Other forests are loading fine, including the sakura and spruce.

**Comment by BiomeBundle** [comment]
Not reproducible or reported by anyone else, closing for now.
