### ISSUE TITLE
Biome Bundle - Optifine Crash

### ISSUE THREAD

**Issue by RodrigoTaipe93** [BiomeBundle/BiomeBundle#156]
Hey, MC and OTG,

There seems to be an issue with the mod:

The crash

- https://paste.ee/p/hJ1bH

My latest log:

- https://mega.nz/#!R4cAVAJD!ozednj7fLPQGfCTZcskLc-WtaFlrVcjEcXFZoEzgyZU

https://imgur.com/a/hO2fTt4

**Comment by RodrigoTaipe93** [comment]
Let's see...I created this world while I was offline. Then I tried to open it up online, and it worked! However, I tried to opened it up again, offline. To check if I could play Minecraft with all my mods offline.



Here are the crashes that I got. With and without Optifine (and the latest log of each time I tried):



- https://mega.nz/#F!kk0GwCAA!6r7bIoA2-RMWFod1CFgeVQ

**Comment by RodrigoTaipe93** [comment]
I tried to opened my world online this time online with and without Optifine. This was the crash I got:

- https://mega.nz/#F!x58S3ahZ!gQ4TU0z71p1MM1QxaOmlKA

**Comment by MCPitman** [comment]
Have you tried updating Optifine? I haven't been able to replicate this.
