### ISSUE TITLE
Worley's Caves

### ISSUE THREAD

**Issue by Oraiz** [BiomeBundle/BiomeBundle#159]
I've made a small custom pack, and have used Biome Bundle for my world gen, but also included Worley's Caves as I wanted a more expansive underground. However caves are seemingly unaffected!
Both mods have default configs, and as far as I know, there is no other mod that would change terrain generation (all I can think is Quark's realistic, which I've turned off).

Any help would be appreciated, and I can provide any other details that might help.

Thanks in advance.

**Comment by alfuken** [comment]
AFAIK, OTG (Open Terrain Generator) uses it's own world generator, which is too custom. And Worley's caves, as well as Swiss Cheese do not affect OTG worlds. OTG is known to be incompatible with a huge amount of mods these days. Which is a shame, as biomes from biome bundle is quite beautiful.

**Comment by MCPitman** [comment]
Worleys isn't compatible with OTG and there's nothing I can do about this on the Biome Bundle side, the same is true with other cave modification mods.

The only other known incompatibilities with OTG are other mods which add biomes to the overworld and other mods which have somewhat duplicate functionality with OTG, other than that I'm not sure what the "huge amount of mods" are that @alfuken is talking about.
