### ISSUE TITLE
Server crashes a few minutes in...

### ISSUE THREAD

**Issue by CreeperBossVJ** [BiomeBundle/BiomeBundle#16]
Hey, whenever I enable your mod on my 1.10.2 server it crashes. I've tried running it without the world named "world" and without the edited generation and it works fine but once I change it back it crashes after I walk around a minute. I did the mineshaft thing already. Here is the crash report:
[crash-2017-01-05_13.34.18-server.txt](https://github.com/BiomeBundle/BiomeBundle/files/688049/crash-2017-01-05_13.34.18-server.txt)

**Comment by MCPitman** [comment]
It seems to be something to do with Quark stone generation interacting with villages somehow, it's strange that it crashes since the stone seems to generate fine as do other Quark worldgen features.

Since disabling villages is not really a valid option for most people, the best workaround for this would be to disable Quark stone generation and generate it using Terrain Control by adding it to the biome configs en masse using find/replace, which if you are interested in doing I can help with.

It has been reported over at the TC bug tracker too:

https://github.com/MCTCP/TerrainControl/issues/499

I will do some testing with Quark and see if I can narrow down the cause.

**Comment by CreeperBossVJ** [comment]
Um, I'm not too handy with mod packs this is my first one I've created in a while, but I willing to help and/or do whatever I need to do.  I don't quite know how to use Terrain Control so I will just disable the stone for now.

**Comment by CreeperBossVJ** [comment]
@MCPitman 
So, I know it is not your mod, but do you know how I would disable the thing causing the problem. I can't figure it out.

**Comment by CreeperBossVJ** [comment]
@MCPitman  I don't think it quark, I removed the mod and recreated the world and the same thing happened.
[crash-2017-01-05_16.33.31-server.txt](https://github.com/BiomeBundle/BiomeBundle/files/688451/crash-2017-01-05_16.33.31-server.txt)

**Comment by MCPitman** [comment]
Let me do some testing @CreeperBossVJ and I'll get back to you.

**Comment by CreeperBossVJ** [comment]
@MCPitman 
Okay, Also I found that when I try the "tc biome" command It says that terrain control isn't enabled, but it definitely is because the world looks different.

**Comment by ScratchyUK** [comment]
It's mineshaft generation causing the issue. Biome Bundle posted about it a few days ago confirming. You need to go into the worldconfig.ini file in the world folder of the TerrainControl config folder and set MineshaftsEnable to false. It means no mineshafts for now but it's better than nothing.

Here's the post: https://github.com/BiomeBundle/BiomeBundle/issues/12

**Comment by LordSmellyPants** [comment]
A new version of Biome Bundle can be downloaded from Curse ([Forge](https://minecraft.curseforge.com/projects/biome-bundle)) or Github ([Bukkit](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0)). I expect this version to fix the issue you are experiencing, a brief changelog can be found [here](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0).

Biome Bundle is now dependant on [Open Terrain Generator](https://minecraft.curseforge.com/projects/open-terrain-generator) and the installation process has changed; head over to the [installation instructions](https://github.com/BiomeBundle/BiomeBundle/wiki/Installation-Instructions) that detail how to install Biome Bundle.

Please bear in mind you will need to generate a new world with the latest update as it is not compatible with old worlds. 

Happy Exploring! ☻
