### ISSUE TITLE
Sponge server with OTG and Biome Bundle

### ISSUE THREAD

**Issue by byaialele** [BiomeBundle/BiomeBundle#161]
For various reasons I am trying to make a sponge server. I am using OTG and Biome bundle, which are both included in the " Life in the village" server modpack. ( Note: I have added some other mods to my game that I like )I know there is no problem with the added mods because singleplayer works just fine. It says there is a problem with OTG and sponge chunk generation in the crashlogs. The server crashes after " Loading configs for world 'Biome Bundle' ". Any help would be greatly appreciated.  Crash logs: 
[crash-2019-03-30_19.16.25-server.txt](https://github.com/BiomeBundle/BiomeBundle/files/3026075/crash-2019-03-30_19.16.25-server.txt)

**Comment by MCPitman** [comment]
OTG doesn't support Sponge, use a supported platform like Forge.
