### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by Eventide215** [BiomeBundle/BiomeBundle#163]
I recently tried to install a modpack named Mystical Village 2 through Twitch. However, the pack would not install and would give an error:

"The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters"

I then found that it was connected to the way this mod's folder structure is. This mod has a huge nest of folders (119 folders in total). Some of these nests are redundant and need to be shortened in order to prevent this error from happening. An example of which is: 

"Biome Bundle\WorldObjects\Rocks\Stone\patchyrocks\patchyrock\"

This could be shortened to something like: "Rocks\patchyrocks". I understand the idea of nesting folders for organization, but this is too far, and causing issues on a few select PCs due to the file path becoming far too long for Windows.

When I went looking for the details exactly I found that in total the path character amount, for my computer, was about 211 on Twitch when unzipping. This is however below the 248 limit for Windows. Though this 211 figure doesn't account for the entire path and file names as well.

**Comment by BiomeBundle** [comment]
having 3 subfolders is fine imo and hasn't been causing issues for anyone else
