### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by warmachine91590** [BiomeBundle/BiomeBundle#164]
Alright, I wanted to add a more complex type of mod that is like this. I got to say it is possibly one of the coolest to me anyway. The one major glaring issue I have is that I did this to my Pixelmon mod pack. The thing is no pokemon spawn I even forced spawned myself to a plain biome and there was no pokemon. When I type the code /spawning or /spawner. It just says it's on and the apricots and other berries are there but no pokemon does anyone know what to do.

**Comment by BiomeBundle** [comment]
Not a bug or problem so doesn't belong here, pixelmon configs have the spawn settings
