### ISSUE TITLE
Biomes changing/losing color

### ISSUE THREAD

**Issue by NifastGS** [BiomeBundle/BiomeBundle#166]
Ever since I started playing with Biome Bundle on, every biome looked as it was supposed to look like. However, recently some Biomes started to show different colored leaves and grass than what they should show. Here are some examples:

Forest Ender biome some days ago vs now:
![2019-08-25_18 27 19](https://user-images.githubusercontent.com/54746402/64125475-6ab6a580-cdaa-11e9-909d-de3890e38bd4.png)
![2019-08-31_13 43 48](https://user-images.githubusercontent.com/54746402/64125498-7b671b80-cdaa-11e9-9d3b-ed711bfc53b9.png)

Weird color border in a biome I found today:
![2019-09-02_12 20 31](https://user-images.githubusercontent.com/54746402/64125500-7dc97580-cdaa-11e9-85e6-3a90e7091080.png)

Some biomes' colors completely changed:
![2019-08-31_13 08 13](https://user-images.githubusercontent.com/54746402/64125503-815cfc80-cdaa-11e9-9d1a-9f69a235f529.png)
![2019-08-31_12 53 32](https://user-images.githubusercontent.com/54746402/64125505-828e2980-cdaa-11e9-850c-65357be9f81e.png)

Here is the latest log of the Minecraft world:

[2019-09-02-3.log](https://github.com/BiomeBundle/BiomeBundle/files/3566630/2019-09-02-3.log)

I put mods that I recently took out from the game back and took out mods that I installed some days ago, but the colors still looked the same.

**Comment by BiomeBundle** [comment]
Was fixed on OTGs end.
