### ISSUE TITLE
Crashing when used with other mods

### ISSUE THREAD

**Issue by Dapperwbs** [BiomeBundle/BiomeBundle#172]
Im not sure what mod it is but its always ALWAYS a Nullpointerexception: Exception Ticking World error. What do i do?

Thanks in advance

**Comment by RodrigoTaipe93** [comment]
Try posting the crash log and also the list of mods that you are using.

If by any chance you are using Biomes O'Plenty with this, try to disable the Biomes of Biomes O'Plenty that have the same ID than BB.

Also, if you are using Roguelike Dungeons or Gravestone mod - Graves, expect crashes

**Comment by BiomeBundle** [comment]
Too vague
