### ISSUE TITLE
Trees don't spawn within some biomes.

### ISSUE THREAD

**Issue by officialnice** [BiomeBundle/BiomeBundle#179]
Custom tress from BB wasn't loading in, specifically within the Webbed Forest and Ender Forest.
![2020-07-06_13 58 50](https://user-images.githubusercontent.com/67922980/86625333-ef59ed80-bf92-11ea-8ab3-7fc9a759d5aa.png)
![2020-07-06_14 06 36](https://user-images.githubusercontent.com/67922980/86626109-3a283500-bf94-11ea-82dd-69d0dcabd894.png)

**Comment by BiomeBundle** [comment]
Looks like a problem on your end, this isn't happening to other people.

Try re-installing and let me know if the issue persists.
