### ISSUE TITLE
Space in world name

### ISSUE THREAD

**Issue by nicholasrobertm** [BiomeBundle/BiomeBundle#180]
Hi there! Currently Biome Bundle requires the world name to be 'Biome Bundle' to work. Biome bundle itself now works with sponge great however there being a space in the world name, this breaks many plugins since this is not a convention / expected (even most mods do things like DIM-1 or one word names). Could the world name for this be migrated to BiomeBundle instead, or is there another way to allow for Biome Bundle to generate with a custom world name?

Appreciate any help!

**Comment by BiomeBundle** [comment]
You can just rename the folder in mods(or plugins)/openterraingenerator/worlds
