### ISSUE TITLE
How would I go about completely disabling all ore generation?

### ISSUE THREAD

**Issue by dtoxftw** [BiomeBundle/BiomeBundle#181]
Do I have to go through all 445 .bc files? (please say no, please say no, please say no) lol

I'm creating a R.A.D. + SkyFactory modpack. So I would like there to be no coal/iron/diamond/ect ect

**Comment by BiomeBundle** [comment]
Yes you do have to change every biome config, but you can use a text editor like notepad++ to find and replace the whole folder at once.

If you replace 
`Ore(IRON_ORE,9,20,100.0,0,63,STONE:0)`

With
`#Ore(IRON_ORE,9,20,100.0,0,63,STONE:0)`

in all files in the WorldBiomes folder it will comment out the line and make it no longer function.
