### ISSUE TITLE
BetterDiving compatibility 

### ISSUE THREAD

**Issue by disastercube** [BiomeBundle/BiomeBundle#184]
BetterDiving mod ads the ability of spawning features in water such as seagrass and if it doesn't work on modded biomes, then you can add them in the config file. I tried many different ways on BiomeBundle biomes but it still doesn't work. I'm wondering whether I'm doing something wrong or does BiomeBundle not work correctly with water sources. (I tried turning ImprovedRivers in bc file as well)

**_Example from one testes biome:_**

modid:biome_name
----------------------------------------------------
OpenTerrainGenerator:ForestEnchanted
                OpenTerrainGenerator:ForestEnchanted
                OpenTerrainGenerator:Forest_Enchanted
                Open_Terrain_Generator:Forest_Enchanted
                Open_Terrain_Generator:ForestEnchanted
                Forest_Enchanted
                ForestEnchanted
                OTG:Forest_Enchanted
                OTG:ForestEnchanted
                BiomeBundle:Forest_Enchanted
                Biome_Bundle:ForestEnchanted
                Biome_Bundle:Forest_Enchanted
                BiomeBundle:ForestEnchanted
                CustomBiomes:ForestEnchanted
                Custom_Biomes:ForestEnchanted
                CustomBiomes:Forest_Enchanted
                Custom_Biomes:Forest_Enchanted
                OpenTerrainGenerator:65
                Open_Terrain_Generator:65
                65
                OTG:65
                BiomeBundle:65
                Biome_Bundle:65
                CustomBiomes:65
                Custom_Biomes:65
                OpenTerrainGenerator:RiverEnchantedForest
                OpenTerrainGenerator:River_Enchanted_Forest
                Open_Terrain_Generator:RiverEnchantedForest
                Open_Terrain_Generator:River_Enchanted_Forest
                River_Enchanted_Forest
                RiverEnchantedForest
                OTG:RiverEnchantedForest
                OTG:River_Enchanted_Forest
                BiomeBundle:River_Enchanted_Forest
                Biome_Bundle:RiverEnchantedForest
                Biome_Bundle:River_Enchanted_Forest
                BiomeBundle:RiverEnchantedForest
-----------------------------------------------

**Comment by BiomeBundle** [comment]
Use the tellme mod to get biome IDs instead of guessing.

Don't enable improved rivers it breaks things.
