### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by MrFrostmaul** [BiomeBundle/BiomeBundle#19]
Hi,
We are getting this error:
http://pastebin.com/AMBkJngu

All files are uploaded correctly with no files missing :\
Thanks

**Comment by MCPitman** [comment]
This is a biome ID conflict between Biome Bundle Frozen Forest and another mod. You can either edit the WoldConfig.ini to change the ID of Frozen Forest or edit other mods' biome IDs in their configs so there is no overlap.

**Comment by MrFrostmaul** [comment]
Ok, Great. Thank you.
