### ISSUE TITLE
DesertLowlands Biome Creating Holes in Ocean

### ISSUE THREAD

**Issue by Mouse1703** [BiomeBundle/BiomeBundle#20]
A DesertLowlands biome generating next to an Ocean or DeepOcean biome results in the water level suddenly dropping:

Using the latest BiomeBundle (v4) for Bukkit on Spigot 1.10.2.

![2017-01-07_15 22 39](https://cloud.githubusercontent.com/assets/20174159/21745661/a6cc1964-d4ed-11e6-8a40-e5fe192dc946.png)
![2017-01-07_15 22 51](https://cloud.githubusercontent.com/assets/20174159/21745664/bd2e4920-d4ed-11e6-94fe-2af1d36ee32d.png)

**Comment by MCPitman** [comment]
I think I found the cause for this (missing beach biomes), it should not be able to happen in the next update.
