### ISSUE TITLE
My server does not start with the mod on forge

### ISSUE THREAD

**Issue by Sjors2003** [BiomeBundle/BiomeBundle#21]
My server crashes everytime I restart it This is what the console says:
08.01 11:17:54 [Multicraft] Server stopped
08.01 11:17:54 [Multicraft] Not restarting crashed server.
08.01 11:17:54 [Multicraft] Server shut down (starting)
08.01 11:17:53 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
08.01 11:17:53 [Server] INFO at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595) ~[forge1102.jar:?]
08.01 11:17:53 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
08.01 11:17:53 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
08.01 11:17:53 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
08.01 11:17:53 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.forge.TCPlugin.onDedicatedServerPostInit(TCPlugin.java:127) ~[TCPlugin.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.forge.WorldLoader.onServerAboutToLoad(WorldLoader.java:98) ~[WorldLoader.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:171) ~[WorldLoader.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:78) ~[ServerConfigProvider.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:88) ~[ServerConfigProvider.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.configuration.ServerConfigProvider.loadCustomObjects(ServerConfigProvider.java:114) ~[ServerConfigProvider.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.customobjects.CustomObjectCollection.<init>(CustomObjectCollection.java:41) ~[CustomObjectCollection.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.customobjects.CustomObjectCollection.load(CustomObjectCollection.java:63) ~[CustomObjectCollection.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.customobjects.bo3.BO3.onEnable(BO3.java:56) ~[BO3.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.customobjects.bo3.BO3Config.<init>(BO3Config.java:77) ~[BO3Config.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.customobjects.bo3.BO3Config.readConfigSettings(BO3Config.java:199) ~[BO3Config.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.customobjects.bo3.BO3Config.readConfigFunctions(BO3Config.java:209) ~[BO3Config.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.configuration.io.SimpleSettingsMap.getConfigFunctions(SimpleSettingsMap.java:88) ~[SimpleSettingsMap.class:?]
08.01 11:17:53 [Server] INFO at com.khorn.terraincontrol.configuration.ConfigFunctionsManager.getConfigFunction(ConfigFunctionsManager.java:100) ~[ConfigFunctionsManager.class:?]
08.01 11:17:53 [Server] INFO java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
08.01 11:17:53 [Server] Server thread/ERROR [FML]: Caught exception from terraincontrol
08.01 11:17:53 [Server] Server thread/ERROR [FML]: The following problems were captured during this phase
08.01 11:17:53 [Server] INFO UCHIE	terraincontrol{2.8.2-SNAPSHOT} [TerrainControl] (terraincontrol-forge-2.8.2-1.10.2-B1.jar) 
08.01 11:17:53 [Server] INFO UCHIJ	Forge{12.18.1.2049} [Minecraft Forge] (forge1102.jar) 
08.01 11:17:53 [Server] INFO UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge1102.jar) 
08.01 11:17:53 [Server] INFO UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
08.01 11:17:53 [Server] INFO States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
08.01 11:17:53 [Server] Server thread/ERROR [FML]: 
08.01 11:17:53 [Server] Server thread/ERROR [FML]: Fatal errors were detected during the transition from POSTINITIALIZATION to AVAILABLE. Loading cannot continue
08.01 11:17:02 [Server] Server thread/INFO [TerrainControl]: Loading configs for world "world"..
08.01 11:17:02 [Server] Server thread/INFO [FML]: Itemstack injection complete
08.01 11:17:02 [Server] Server thread/INFO [FML]: Injecting itemstacks
08.01 11:17:02 [Server] Server thread/INFO [TerrainControl]: 22 Global custom objects loaded
08.01 11:17:02 [Server] Forge Version Check/INFO [ForgeVersionCheck]: [Forge] Found status: OUTDATED Target: 12.18.3.2185
08.01 11:17:01 [Server] Server thread/INFO Using epoll channel type
08.01 11:17:01 [Server] Server thread/INFO Starting Minecraft server on mike.kaashosting.nl:25619
08.01 11:17:01 [Server] Server thread/INFO Generating keypair
08.01 11:17:01 [Server] Server thread/INFO Default game type: SURVIVAL
08.01 11:17:01 [Server] Server thread/INFO Loading properties
08.01 11:17:01 [Server] Server thread/INFO [FML]: Itemstack injection complete
08.01 11:17:01 [Server] Server thread/INFO [FML]: Injecting itemstacks
08.01 11:17:01 [Server] Server thread/INFO [FML]: Holder lookups applied
08.01 11:17:01 [Server] Server thread/INFO [FML]: Applying holder lookups
08.01 11:17:01 [Server] Forge Version Check/INFO [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
08.01 11:17:01 [Server] Server thread/INFO [FML]: Configured a dormant chunk cache size of 0
08.01 11:17:01 [Server] Server thread/INFO [FML]: Found 0 ItemStackHolder annotations
08.01 11:17:01 [Server] Server thread/INFO [FML]: Identifying ItemStackHolder annotations
08.01 11:17:01 [Server] Server thread/INFO [FML]: Found 423 ObjectHolder annotations
08.01 11:17:01 [Server] Server thread/INFO [FML]: Processing ObjectHolder annotations
08.01 11:17:01 [Server] Server thread/INFO [FML]: Attempting connection with missing mods [mcp, FML, Forge, terraincontrol] at SERVER
08.01 11:17:01 [Server] Server thread/INFO [FML]: Attempting connection with missing mods [mcp, FML, Forge, terraincontrol] at CLIENT
08.01 11:17:01 [Server] Server thread/INFO [FML]: Forge Mod Loader has identified 4 mods to load
08.01 11:17:01 [Server] Server thread/WARN [terraincontrol]: Mod terraincontrol is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 2.8.2-SNAPSHOT
08.01 11:17:00 [Server] Server thread/INFO [FML]: Searching /mods for mods
08.01 11:17:00 [Server] Server thread/INFO [FML]: Found 0 mods from the command line. Injecting into mod discoverer
08.01 11:17:00 [Server] Server thread/INFO [FML]: Replaced 233 ore recipes
08.01 11:17:00 [Server] Server thread/INFO [FML]: MinecraftForge v12.18.1.2049 Initialized
08.01 11:17:00 [Server] Server thread/WARN To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
08.01 11:17:00 [Server] Server thread/INFO Starting minecraft server version 1.10.2
08.01 11:16:54 [Server] main/INFO [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
08.01 11:16:54 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
08.01 11:16:54 [Server] main/INFO [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
08.01 11:16:53 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
08.01 11:16:53 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
08.01 11:16:53 [Server] main/INFO [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
08.01 11:16:52 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
08.01 11:16:52 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
08.01 11:16:52 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
08.01 11:16:52 [Server] main/INFO [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
08.01 11:16:52 [Server] main/INFO [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
08.01 11:16:52 [Server] main/INFO [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_91, running on Linux:amd64:3.16.0-4-amd64, installed at /usr/lib/jvm/java-8-oracle/jre
08.01 11:16:52 [Server] main/INFO [FML]: Forge Mod Loader version 12.18.1.2049 for Minecraft 1.10.2 loading
08.01 11:16:52 [Server] INFO 2017-01-08 11:16:52,273 WARN Disabling terminal, you're running in an unsupported environment.
08.01 11:16:50 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
08.01 11:16:50 [Server] main/INFO [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
08.01 11:16:50 [Server] main/INFO [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
08.01 11:16:49 [Multicraft] Updating eula.txt file
08.01 11:16:49 [Multicraft] Loaded config for "Mod: Forge (1.10.2)"
08.01 11:16:49 [Multicraft] Starting server!

**Comment by MCPitman** [comment]
My guess would be it is due to the Forge you have installed being 5 months / 85 versions out of date. Try with an up to date Forge.

**Comment by Sjors2003** [comment]
Oke thanks!
