### ISSUE TITLE
Biome Bundle and Mo Creatures crash

### ISSUE THREAD

**Issue by Sandriell** [BiomeBundle/BiomeBundle#22]
I am unsure what mod would be causing this/needs a fix, so I figured I would report it here and with the Mo Creatures team.

Log: https://gist.github.com/Sandriell/68f4e0d25a77ce892040cff35540290a

MC: 1.10.2 w Forge 12.18.3.2185

If you need more info, let me know!

**Comment by MCPitman** [comment]
Bug already reported, going to close this one and link it in the [existing report](https://github.com/BiomeBundle/BiomeBundle/issues/13).
