### ISSUE TITLE
FlyingForest biome exposing bedrock underwater

### ISSUE THREAD

**Issue by Mouse1703** [BiomeBundle/BiomeBundle#27]
The FlyingForest biome tends to generate with massive swaths of bedrock exposed underwater, often bordered by underwater spikes where it meets an Ocean biome. FloatingIslands biome does not have this issue and generates beautifully.

Using BiomeBundle (v4) for Bukkit on Spigot 1.10.2.

![2017-01-09_21 01 33](https://cloud.githubusercontent.com/assets/20174159/21793510/4dbf6f4c-d6af-11e6-9f78-5458a4af3562.png)
![2017-01-09_20 56 45](https://cloud.githubusercontent.com/assets/20174159/21793553/8f6b187e-d6af-11e6-82ff-7de30f6f183f.png)

**Comment by MCPitman** [comment]
This isn't actually a bug, the underwater section of flying forest is impacted by the terrain settings needed to create the biome. The terrain in Flying Forest and FloatingIslands is very different.

This is the primary reason Flying Forest only appears in the ocean.
