### ISSUE TITLE
I can't create a world

### ISSUE THREAD

**Issue by ThanhNguye** [BiomeBundle/BiomeBundle#28]
I created a world name "world" then the screen was loading terrain for 2 hours (I put all the files in to the correct folder)

**Comment by MCPitman** [comment]
Try dedicating 2gb RAM or more to Minecraft.

**Comment by ThanhNguye** [comment]
HOW?????

**Comment by BiomeBundle** [comment]
Start the Minecraft launcher. 
Select your profile. 
Enable JVM Arguments. 
Allocate more RAM. 
Save your profile.
Run Minecraft.

**Comment by ThanhNguye** [comment]
Is it another way to fix this issue?

**Comment by ThanhNguye** [comment]
It didn't work.

**Comment by BiomeBundle** [comment]
Hmm it should work -here's a much better explanation on how to dedicate 2gb RAM

https://www.youtube.com/watch?v=2ev7AatHhiQ

**Comment by ThanhNguye** [comment]
This is an error:
"Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release"
So what can i do?

**Comment by BiomeBundle** [comment]
I'm not sure what to suggest as this isn't really a Biome Bundle issue. Other than giving this walkthrough a go on allocating memory http://kehaan.me/?p=522 else try troubleshooting the error

**Comment by ThanhNguye** [comment]
Thanks anyway
