### ISSUE TITLE
World crashing

### ISSUE THREAD

**Issue by MartoA** [BiomeBundle/BiomeBundle#29]
Hey there, I really love your work here. This mod is the awesomest thing I found in minecraft for so many years, hehe. Problem is that I play with few more mods on, and when I get from nether to overworld the world crashes.

This is the last crash report I got. Any idea why this is happening? Thank you for your work!
[crash-2017-01-10_15.53.36-server.txt](https://github.com/BiomeBundle/BiomeBundle/files/696643/crash-2017-01-10_15.53.36-server.txt)

**Comment by MCPitman** [comment]
Hi,

This has been fixed in the latest update (4.1). You should be able to safely update worlds from v4.
