### ISSUE TITLE
Feature: From Image Functionality

### ISSUE THREAD

**Issue by LISTINGS09** [BiomeBundle/BiomeBundle#3]
TC supports a 'From Image' mode, this doesn't work with BB because each custom biome does not have a unique hex color code.

If these unique hex colors were added, it would both show the correct biome types when exported in /tc map and also allow a BB world to be generated from an image.

From there a template png could be created for players to load and showcase all the biomes BB has to offer.

**Comment by BiomeBundle** [comment]
Thanks for the feedback.

If we were to develop a frame image version we would want to do it properly from scratch and at the moment there are no plans to do that. Although there is nothing stopping you adding in the hex colours if you wanted to.
