### ISSUE TITLE
1.8 please!

### ISSUE THREAD

**Issue by Firelawa** [BiomeBundle/BiomeBundle#32]
Hey! When i saw this biome pack i really wanted to try this out with my little brother. But i cannot play splitscreen with him since the Joypad mod is only in 1.8 and below. So i wanted to ask if you could make this work with 1.8. Thanks!

**Comment by MCPitman** [comment]
This is not the correct place for these kinds of requests. I saw you posted on the [subreddit ](https://www.reddit.com/r/biomebundle/comments/5ncghq/please_make_this_work_in_18_forge/)and will respond there.
