### ISSUE TITLE
Crash on server start up, "Biome Autumnal Woods not found".

### ISSUE THREAD

**Issue by Apocryphai** [BiomeBundle/BiomeBundle#34]
Server running modified AllTheMods instance, crash log here: 
https://zerobin.net/?3e01fdf9be230814#ruypPFdhs+cCBvrk+1iasFpn3A4zFXDwZjsIUqvJpQo=

**Comment by MCPitman** [comment]
Biome ID conflict, not a bug.

Please read the [FAQ ](https://sites.google.com/site/biomebundle/faq)section on mod compatibility before posting bug reports.
