### ISSUE TITLE
Freeze with the latest version of BB

### ISSUE THREAD

**Issue by Tschipp** [BiomeBundle/BiomeBundle#35]
The game freezes when creating a world, throwing this error:
http://pastebin.com/YNGvEswT

The first line probably says everything.

**Comment by MCPitman** [comment]
Biome ID conflict.

Please try to view closed reports before submitting a new one. This has been reported many times before and is user error:

https://github.com/BiomeBundle/BiomeBundle/issues/34
https://github.com/BiomeBundle/BiomeBundle/issues/11
https://github.com/BiomeBundle/BiomeBundle/issues/19
