### ISSUE TITLE
Simple Dimensions Mod Compability

### ISSUE THREAD

**Issue by WenXin20** [BiomeBundle/BiomeBundle#36]
Would it be possible to add compatibility for this? This mod makes it able to create dimensions in game by using world options. If it were made possible, then I could make a normal world, but create a dimension with the terrain control option. It currently says terrain control isn't enabled for the world in the custom dimension.

**Comment by BiomeBundle** [comment]
The latest version of Biome Bundle relies upon Open Terrain Generator which has it's own ability to generate dimensions. Check out [OTG.](https://minecraft.curseforge.com/projects/open-terrain-generator) 

A new version of Biome Bundle can be downloaded from Curse ([Forge](https://minecraft.curseforge.com/projects/biome-bundle)) or Github ([Bukkit](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0)). A brief changelog can be found [here](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0).

Biome Bundle's installation process has changed; head over to the [installation instructions](https://github.com/BiomeBundle/BiomeBundle/wiki/Installation-Instructions) that detail how to install BB.

**Comment by WenXin20** [comment]
Ok, thanks
