### ISSUE TITLE
[1.10.2] Forestry butterflies crashing with BiomeBundle

### ISSUE THREAD

**Issue by drewbit** [BiomeBundle/BiomeBundle#37]
See this: 
https://github.com/ForestryMC/ForestryMC/issues/1574#issuecomment-27430532

Using Biome Bundle Version: Biome Bundle for 1.10 Forge (v4.1)

**Comment by BiomeBundle** [comment]
A new version of Biome Bundle can be downloaded from Curse ([Forge](https://minecraft.curseforge.com/projects/biome-bundle)) or Github ([Bukkit](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0)). I expect this version to fix the issue you are experiencing, a brief changelog can be found [here](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0).

Biome Bundle is now dependant on [Open Terrain Generator](https://minecraft.curseforge.com/projects/open-terrain-generator) and the installation process has changed; head over to the [installation instructions](https://github.com/BiomeBundle/BiomeBundle/wiki/Installation-Instructions) that detail how to install Biome Bundle.

Please bear in mind you will need to generate a new world with the latest update as it is not compatible with old worlds. 

Happy Exploring! ☻
