### ISSUE TITLE
Small typo in castle1

### ISSUE THREAD

**Issue by BakermanLP** [BiomeBundle/BiomeBundle#4]
https://github.com/BiomeBundle/BiomeBundle/blob/master/TerrainControl/worlds/world/WorldObjects/Structures/BranchingStructures/Castle/Castle1.BO3#L7062

There is the small typo RandomBlockBlock should be RandomBlock.

But that is a small thing

**Comment by BiomeBundle** [comment]
Hey Bakerman thanks for the feedback.

This has now been fixed in the branch but has not yet been updated into the main release

https://github.com/BiomeBundle/BiomeBundle/issues/2

**Comment by BakermanLP** [comment]
No problem is easy fixed
