### ISSUE TITLE
Java crash on server.

### ISSUE THREAD

**Issue by Apocryphai** [BiomeBundle/BiomeBundle#41]
I'm running the latest version of BiomeBundle in a modified AllTheMods pack, MC 1.10.2, and am getting a JRE crash on the server sometimes when there's nobody on. Here's the crash log:

https://zerobin.net/?8be362135a39bfc4#URNRcE242wFNdRQyDoPjZLUcCTEa23fCjghstJ84BXk=

Let me know what other information would be helpful! Thanks.

**Comment by BiomeBundle** [comment]
A new version of Biome Bundle can be downloaded from Curse ([Forge](https://minecraft.curseforge.com/projects/biome-bundle)) or Github ([Bukkit](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0)). I expect this version to fix the issue you are experiencing, a brief changelog can be found [here](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0).

Biome Bundle is now dependant on [Open Terrain Generator](https://minecraft.curseforge.com/projects/open-terrain-generator) and the installation process has changed; head over to the [installation instructions](https://github.com/BiomeBundle/BiomeBundle/wiki/Installation-Instructions) that detail how to install Biome Bundle.

Please bear in mind you will need to generate a new world with the latest update as it is not compatible with old worlds. 

Happy Exploring! ☻
