### ISSUE TITLE
Every World Only Renders Ice Biomes v.4.1

### ISSUE THREAD

**Issue by Maskobi** [BiomeBundle/BiomeBundle#43]
I've been playing around with this mod for awhile and even after 20 new worlds (with a default config file) and my worlds only generate ice-type biomes

Here's a list of my efforts to change this:
- BiomeMode: Normal or FromImage
- Trying specific seeds
- Reverting back to v4.0 config files
- Exploring worlds for other biomes thoroughly 
        *Note* I can find a few islands with green mountain biomes

FINALLY
I've since manually deleted all ice biome types from the config files and upon rendering a new world, I only get small, sandy islands.

**Edit** It seems there is a possibility for other biomes to render, but they only do so on small islands surrounded by ocean.

**Comment by MCPitman** [comment]
Not a bug, looks like user error. Discussion continued on the subreddit here:

https://www.reddit.com/r/biomebundle/comments/5weu89/every_world_only_renders_ice_biomes_v41/
