### ISSUE TITLE
BiomeBundle seems to have no change on new worlds

### ISSUE THREAD

**Issue by BaneofOdacer** [BiomeBundle/BiomeBundle#44]
When I start a new world it appears as if nothing has changed -- no new biomes just stereotypical minecraft biomes. I have looked around many different worlds and haven't found any new biomes. 

I followed the install directions exactly. Is there something I am missing?

Thanks for any help! 

Single Player

    Download and install the latest recommended forge for 1.10.2.
	Run Minecraft once to have forge create the /mods and /config folders.
    Put the downloaded TerrainControl .jar in .minecraft/mods and the TerrainControl folder in .minecraft/config.
    On the normal world creation screen ensure to name your world 'world' and click 'more world options', changing 'World Type' to 'Terrain Control'.

**Comment by Neeley-Justen** [comment]
Reinstall and report back. Disclaimer: not a contributor, but reinstall solved this for me.

**Comment by Bestfreestylist** [comment]
new world has to be named  "world"

**Comment by BiomeBundle** [comment]
The latest version of Biome Bundle for Forge is now a Jar you can drop in your mods folder; you also need to install Open Terrain Generator which BB now relies upon. Here is a copy pasta message I am passing around. 

A new version of Biome Bundle can be downloaded from Curse ([Forge](https://minecraft.curseforge.com/projects/biome-bundle)) or Github ([Bukkit](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0)). I expect this version to fix the issue you are experiencing, a brief changelog can be found [here](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0).

Biome Bundle is now dependant on [Open Terrain Generator](https://minecraft.curseforge.com/projects/open-terrain-generator) and the installation process has changed; head over to the [installation instructions](https://github.com/BiomeBundle/BiomeBundle/wiki/Installation-Instructions) that detail how to install Biome Bundle.

Please bear in mind you will need to generate a new world with the latest update as it is not compatible with old worlds. 

Happy Exploring! ☻
