### ISSUE TITLE
MOD CONFLICT: Pam's Harvestcraft  1.9.4-1.10.2h 

### ISSUE THREAD

**Issue by Neeley-Justen** [BiomeBundle/BiomeBundle#45]
Appears to be a conflict between the graveyard village and the bush generation of Harvestcraft.  Harvestcraft removal solved issue, just a heads-up.

[crash-2017-03-10_07.08.45-server.txt](https://github.com/BiomeBundle/BiomeBundle/files/834305/crash-2017-03-10_07.08.45-server.txt)

**Comment by PCobald** [comment]
Update your graphic card.
This article can be help look at the win 7 link.
http://support.amd.com/it-it/kb-articles/pages/AMDCatalystOpenGL42BetaWin.aspx

**Comment by Neeley-Justen** [comment]
While I thank you for reminding me to update my drivers ( I caught a couple of bottlenecks in firmware,) This is not a graphics card issue. Two mods are rendering at the same location, presumably because this mod has almost no compatibility adjustments, I actually removed it from my build because it does not use the forge biome dictionary, breaking several mods.
