### ISSUE TITLE
FPS issue

### ISSUE THREAD

**Issue by SquishyPyukumuku** [BiomeBundle/BiomeBundle#47]
I have a custom gaming pc that can normally run minecraft at 500+ fps, but for some reason playing on a world with this mod drops my frames to less than one. I've tried reinstalling the mod, but it hasn't helped. I'm wondering is there is something else I could try, or do I just need a better computer to run this.

**Comment by BiomeBundle** [comment]
Have you allocated more memory to Minecraft?

**Comment by MCPitman** [comment]
Appears to be a memory issue, allocate more memory to Minecraft and let us know if the problem persists.
