### ISSUE TITLE
Download not available 

### ISSUE THREAD

**Issue by MY200378** [BiomeBundle/BiomeBundle#49]
after going to the official biome bundle site <https://sites.google.com/site/biomebundle/downloads>, I clicked the "download", then I was bring to a Minecraft curseforge site which says "Not found
We were unable to find the page or file you were looking for." <https://minecraft.curseforge.com/projects/biome-bundle/files>

**Comment by Br00k3star** [comment]
Im having the same issue. hope someone is working on it

**Comment by DanNetwalker** [comment]
Same here, and It's blocking the modpacks using this mod. Please help?

**Comment by BiomeBundle** [comment]
A new version of Biome Bundle can be downloaded from Curse ([Forge](https://minecraft.curseforge.com/projects/biome-bundle)) or Github ([Bukkit](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0)). I expect this version to fix the issue you are experiencing, a brief changelog can be found [here](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0).

Biome Bundle is now dependant on [Open Terrain Generator](https://minecraft.curseforge.com/projects/open-terrain-generator) and the installation process has changed; head over to the [installation instructions](https://github.com/BiomeBundle/BiomeBundle/wiki/Installation-Instructions) that detail how to install Biome Bundle.

Please bear in mind you will need to generate a new world with the latest update as it is not compatible with old worlds. 

Happy Exploring! ☻
