### ISSUE TITLE
World creation screen problem

### ISSUE THREAD

**Issue by BlaaBlaaa** [BiomeBundle/BiomeBundle#5]
Your Instruction page says:_"make sure you select 'bbundle'_ on the world create screen!"

I have the 1.10 Beta and i cant select it is that normal in 1.10?

**Comment by MCPitman** [comment]
Do you mean here? https://sites.google.com/site/biomebundle/downloads

It says that under forge 1.7.10 single player. The 1.10 version is for Spigot servers only.

**Comment by BlaaBlaaa** [comment]
Ohh.. why? Is there any way for singleplayer :'(

**Comment by BiomeBundle** [comment]
You can create a Spigot server and join from the same computer

**Comment by BiomeBundle** [comment]
Biome Bundle is now available for Forge 1.10.2 so you will be able to launch in single player mode
