### ISSUE TITLE
Customizing the world with Biome Bundle? 

### ISSUE THREAD

**Issue by Tyranuss** [BiomeBundle/BiomeBundle#51]
Hello. Is it possible to customize the world with BB? What I mean is I wanna crank up the dungeons to the max and some other things that you can do with vanilla MC. Unfortunately I don't have the luxury of making iron farms and other resource farms and afk, as I play around 1 hour per day. Can this be done, or?

**Comment by LordSmellyPants** [comment]
Closing this as it's not really an "issue". If you would like to edit biome bundle settings then make a post on [r/biomebundle ](https://www.reddit.com/r/biomebundle/)and someone will help you.

**Comment by Tyranuss** [comment]
I don't have reddit account :S
