### ISSUE TITLE
Too many stone clusters? [Biome Bundle v5]

### ISSUE THREAD

**Issue by Lodugh** [BiomeBundle/BiomeBundle#52]
I dont know if its just me, but I really dont like how it looks with so many different stones in the caves.
I would actually like to turn them off totally and just use the cluster generation of the Quark mod for it(less and bigger clusters). Is there any way to turn them off easily? I'd be glad if somone could help me with that! :)
![2017-04-23_13 53 42](https://cloud.githubusercontent.com/assets/13154183/25313358/30946740-282d-11e7-8187-465d6492bd61.png)

**Comment by LordSmellyPants** [comment]
Closing this as it's not really an "issue". If you would like to edit biome bundle settings then make a post on [r/biomebundle](https://www.reddit.com/r/biomebundle/) and someone will help you.
