### ISSUE TITLE
Unaesthetic ore clusters on the surface[Biome Bundle v5]

### ISSUE THREAD

**Issue by Lodugh** [BiomeBundle/BiomeBundle#53]
I found some coal and iron ore clusters right between some grass or hardened clay blocks, which seemed a little bit out of place there. Saw it mostly in jungle biomes. With stone around it probably wouldn't look as bad.

**Comment by LordSmellyPants** [comment]
Same as before, closing this as it's not really an "issue". If you would like to edit biome bundle settings then make a post on r/biomebundle and someone will help you.
