### ISSUE TITLE
Savanna transition biome beneath cold biome[Biome Bundle v5]

### ISSUE THREAD

**Issue by Lodugh** [BiomeBundle/BiomeBundle#54]
I found very inept savanna transition biomes right beneath a taiga biome. Hopefully that can be fixed with some config changes.
![2017-04-23_20 55 27](https://cloud.githubusercontent.com/assets/13154183/25318054/9254f680-2886-11e7-85d6-4e20d17a0ab3.png)

**Comment by MCPitman** [comment]
This just looks like the edge for the biome, I'm not sure what problem you are reporting?

**Comment by BiomeBundle** [comment]
Lodugh, if you feel that there are any configurations that are not to your liking then by all means please go ahead and edit your copy of the mod. If you would like advice on how to edit configs then please ask on the subreddit at [r/biombundle](https://www.reddit.com/r/biomebundle/). Please do not report "preferences" as issues on the Github. 

Closing issue.
