### ISSUE TITLE
[Biome Bundle v5] Crash when using with Sponge

### ISSUE THREAD

**Issue by LiskoSlayer63** [BiomeBundle/BiomeBundle#55]
The whole server crashes on startup when using with Sponge, I uploaded the crash-log [here](https://pastebin.com/HcguBdH2)

**Comment by MCPitman** [comment]
Sponge is not supported, use Spigot or Forge.

**Comment by LiskoSlayer63** [comment]
@MCPitman I used SpongeForge, it's basically OFrge and Sponge is just a mod which loads plugins. I forgot to mention that.
