### ISSUE TITLE
[Recurrent Complex compatibility] Generated structures in villages are abruptly chopped

### ISSUE THREAD

**Issue by Noodlebrain** [BiomeBundle/BiomeBundle#56]
Non-village structures from Recurrent Complex generate just fine, but village structures from the mod have a tendency to end abruptly.

Screenshots:
http://imgur.com/a/x7K72

**Comment by PSILONCRAFT** [comment]
have the same issue

**Comment by Ivorforce** [comment]
See https://github.com/Ivorforce/RecurrentComplex/issues/197.

**Comment by MCPitman** [comment]
It seems there was a fix on Recurrent Complex's side to address this problem, @Noodlebrain or @PSILONCRAFT can you confirm if the problem still occurs when using OTG + RC?

**Comment by Noodlebrain** [comment]
Using OTG v18 and RCC v1.3.2, the issues are still occurring, sometimes with non-RCC structures as well.

**Comment by MCPitman** [comment]
Non RCC structures?

**Comment by Noodlebrain** [comment]
Non-vanilla village structures like Immersive Engineering's Engineer houses, or Actually Additions' Jam Guy house have also been sometimes cut off, but not as frequently as RCC structures.

**Comment by MCPitman** [comment]
Ah, okay. So custom village buildings from other mods. Thanks.

**Comment by EchenCraft** [comment]
Can also confirm this was also happening as of a few days ago, been doing alot of testing with generators including BOP ATG and RTG and this only sems to be happening now with OTG.. Hope it isnt to hard to track down as otherwise this gen is by far superior to everything else.

**Comment by chland** [comment]
> Can also confirm this was also happening as of a few days ago, been doing alot of testing with generators including BOP ATG and RTG and this time only seems to be happening now with OTG.

I did the same tests a few weeks ago (with the same results) and reported it over at OTG -
 https://github.com/PG85/OpenTerrainGenerator/issues/26

**Comment by ljbarret5** [comment]
Still happening in version 1.4.5.1 for minecraft 1.12.2. Most of the RC village structures are cut off in every village that generates....

**Comment by MCPitman** [comment]
Fixed in the latest OTG for 1.12.2
