### ISSUE TITLE
1.9.2 download

### ISSUE THREAD

**Issue by aycgit** [BiomeBundle/BiomeBundle#59]
since you have removed it from curse where can i download bb for 1.9.2 since i want to keep the 1.9 compatability

**Comment by LordSmellyPants** [comment]
Older versions can be found on the sidebar to the right of the [wiki](https://github.com/BiomeBundle/BiomeBundle/wiki)

**Comment by aycgit** [comment]
so no 1.9.2 version or is the 1.9 version 1.9.x?

**Comment by aycgit** [comment]
@LordSmellyPants the 1.9 version on the wiki seems to just give the vanilla biomes and objects or is that just me?

**Comment by aycgit** [comment]
@LordSmellyPants yes it is indeed broken

**Comment by LordSmellyPants** [comment]
The files are all intact in the download. Unfortunately we do not support those versions anymore, sorry if you can't work it out.
