### ISSUE TITLE
Can't start world with Biome Bundle (forge 1.10.2 singleplayer)

### ISSUE THREAD

**Issue by davi4046** [BiomeBundle/BiomeBundle#60]
Hey Creator of Biome Bundle
I can't start a new world with Biome Bundle. 

It loaded 20 min. and then it said "game crashed". I've tried it 5 times and the same happened. I've downloaded the second newest version of Biome Bundle and OBG the newest.
I've got a good pc so i don't think that that's the issue.

Please help me out. Dear regards David.

**Comment by Sandriell** [comment]
Sounds like you need to allocate more RAM to Minecraft. If you don't know how, google it, there are countless tutorials on how.

**Comment by MCPitman** [comment]
Likely to be a memory issue, please allocate more memory and let us know if the problem persists.
