### ISSUE TITLE
I really need help with this one

### ISSUE THREAD

**Issue by PSILONCRAFT** [BiomeBundle/BiomeBundle#61]
I am the creator of PROJEC PSILONCRAFTED and i use yor mod. its amazing but since i use 153 mods there are bound to be problems. Im sending you this issue because your mod is one that prints out with a error in my setup. i will send you the server log and hope for a proper answer to the adressing issue

Best regards PSILONCRAFT
[crash-2017-04-30_23.33.02-server.txt](https://github.com/BiomeBundle/BiomeBundle/files/967062/crash-2017-04-30_23.33.02-server.txt)

**Comment by MCPitman** [comment]
Solved in OTG v17

https://minecraft.curseforge.com/projects/open-terrain-generator/files/2413721
