### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by PiggyPiglet** [BiomeBundle/BiomeBundle#62]
Hi, on generation, I'm getting this spam. I can't use openterraingenerator since my server is 1.11.
https://hastebin.com/abomewevog.pas

**Comment by MCPitman** [comment]
This is because Terrain Control does not have the ability to place entities in structures, and Biome Bundle v5 uses this feature heavily.

You will have to wait until Open Terrain Generator updates to 1.11.2
