### ISSUE TITLE
Still stuck on generating world...

### ISSUE THREAD

**Issue by neanderthal42** [BiomeBundle/BiomeBundle#65]
Hello again, I had trouble before after starting a new biome bundle world and getting the "generating world" message for hours and hours. It was suggested to me to allocate more RAM to minecraft. I did so, changing it from 1GB to 4GB (my computer has 8GB). This did not work either even though I let the world load for multiple hours. I have also tried using 2GB, 3GB, 6GB, and all 8GB to the same result. Endless world building. Is there anything else I can do?

**Comment by MCPitman** [comment]
It's impossible to know what is going on without seeing the log, could you upload your latest log file where the issue occurs to pastebin.com and post a link to it here?

**Comment by neanderthal42** [comment]
https://pastebin.com/bB5iLcpC

**Comment by MY200378** [comment]
Same problem, it loads forever... like I left the game running for 3 hours and nothin happens.

**Comment by MCPitman** [comment]
Your worldedit version is for Minecraft 1.8.9, the log does not mention OTG/Biome Bundle at all.
