### ISSUE TITLE
Restart stopping generator

### ISSUE THREAD

**Issue by PiggyPiglet** [BiomeBundle/BiomeBundle#66]
Hi, so I've switched to OpenTerrainGenerator but when ever I restart the server, the generator stops working and the world goes to the vanilla gen.
![alt text](http://i.imgur.com/8vHhq42.jpg "Not working")
EDIT: I tried with terraincontrol, same thing happens. I'm using multiverse and I've made the world via /mv create survival normal -g OpenTerrainGenerator
I'm on spigot 1.10.2 and the latest otg and biomebundle. I've made a folder called survival in /plugins/OpenTerrainGenerator/worlds and put the biomebundle stuff into it.

**Comment by MCPitman** [comment]
Cannot recreate this problem at all, and it has not been reported by any other users.

When you say you switched to OTG, you mean from Terrain Control? If so that's the source of the issue because that doesn't work..
