### ISSUE TITLE
ArrayIndexOutOfBoundsException with ids exceeding 4096

### ISSUE THREAD

**Issue by Everett1999** [BiomeBundle/BiomeBundle#67]
Upon generating a world the game will [crash with an ArrayIndexOutOfBoundsException](https://gist.github.com/Everett1999/f47b257eaea21ad80a0e1b4d1dbb560c) if more than 4096 ids are registered through the use of [NotEnoughIds](https://minecraft.curseforge.com/projects/notenoughids).

Originally I thought that this was an Open Terrain Generator issue, but I have been able to generate a world with all of the other currently available OTG presets with more than 4096 ids.

I've been able to reproduce this crash by just adding Open Terrain Generator and Biome Bundle to the [All The Mods](https://mods.curse.com/modpacks/minecraft/242462-all-the-mods) pack, and generating a Biome Bundle world.

The game hangs while generating, and the log reads `[FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.`

**Comment by PeeGee85Spil** [comment]
Hey, thanks for reporting this, will look into it a.s.a.p.

**Comment by G1itch710** [comment]
is there anyway around this or has it been fixed yet?, have this same problem with the same pack

**Comment by PeeGee85Spil** [comment]
Hey guys,

This has been fixed for the next release (v20), we're just tidying things up atm, updating the pre-sets and making sure it's a proper release. Hope to drop it within the next few days (v20).

**Comment by MCPitman** [comment]
This is now fixed in the latest builds of OTG for 1.10.2 and 1.11.2
