### ISSUE TITLE
Vanilla mobs not spawning 

### ISSUE THREAD

**Issue by CacheTellsStories** [BiomeBundle/BiomeBundle#68]
So I have no creatures installed with Biome Bundle. I love both mods very much. However due to the custom spawning both mo creatures and Biome bundle use, vanilla hostile mobs stopped spawning naturally. Is there a way to remove the spawn preferences from the Biome bundle Open Terrain Generator setup?

**Comment by CacheTellsStories** [comment]
*mo creatures

**Comment by MCPitman** [comment]
As you can see on the OTG wiki [here](http://openterraingen.wikia.com/wiki/Installing_OTG#Mod_Compatibility) there are compatibility issues with Mo Creatures Custom Mob Spawner. Try using MoC without it.

**Comment by CacheTellsStories** [comment]
Wait you can use mo creatures without cms? How? I thought mo creatures required CMS.

**Comment by CacheTellsStories** [comment]
How can you use mo creatures without CMS? Do I just remove CMS?
