### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by rckymtnrfc** [BiomeBundle/BiomeBundle#71]
Getting the following crash log and Minecraft locks up.  https://pastebin.com/ZYPbqLvm

I'm only using Minecraft 1.11.2, Forge 2315, OTG 1.11.2-v5 and Biome Bundle 1.11.2-v5.1.

Thanks!

**Comment by hofmannk69** [comment]
I am getting exactly the same crash with same MC, Forge, OTG and BB.

**Comment by SkillzGamingYT** [comment]
same

**Comment by MCPitman** [comment]
@rckymtnrfc @hofmannk69 @SkillzGamingYT 

This seems to be an issue with later builds of Forge, try using the recommended version (13.20.0.2228) until it can be fixed.

**Comment by LordSmellyPants** [comment]
Later builds of Forge are now compatible
