### ISSUE TITLE
[1.11.2] Creating a world freezes the game.

### ISSUE THREAD

**Issue by DeadPigman17** [BiomeBundle/BiomeBundle#73]

**Comment by MCPitman** [comment]
Didn't read the warning on the bbundle curse page? You need to use the
recommended (not latest) forge version.

**Comment by DeadPigman17** [comment]
I'm using that forge version.

**Comment by MCPitman** [comment]
Then it should work. Do you have more than 2gb memory allocated?

**Comment by DeadPigman17** [comment]
Yes.

**Comment by MCPitman** [comment]
Going to need to see the log to work out what is happening.

**Comment by DeadPigman17** [comment]
There it is. Also, I use other mods besides this one, so I tried to use only Biome Bundle, it worked, then I tried to use only the mods I had already installed, it worked too. Can you see in the log what mod is causing the incompatibility?

https://ptpb.pw/xR-W
