### ISSUE TITLE
[1.11.2] Incompatibility with Animania-1.11.2-1.1.4

### ISSUE THREAD

**Issue by DeadPigman17** [BiomeBundle/BiomeBundle#74]
If you create a world with Animania mod (https://minecraft.curseforge.com/projects/animania) the game freezes, and the world doesn't load.

**Comment by MCPitman** [comment]
This is fixed in the latest version.

**Comment by darknat** [comment]
Hi, I play on 1.10.2 version, and with Animania, passive mob no spawn on the Biome bundle's biomes. 

You have an idea ? I saw that I can change the list of the spawning mob in the biome's files, but if you have another idea..
