### ISSUE TITLE
Dimensions from other mod generated in the overworld

### ISSUE THREAD

**Issue by Bjarka1** [BiomeBundle/BiomeBundle#75]
1.11.2 v5.1 As the title says... My modpack includes aether and lightningcraft and both mods dimensions are created in the overworld. And their mobs too. It's not necessarily a bad thing but I assume it's unintentional? It's just adding part of the worlds and no structures so you still need to travel to the actual dimension in order to complete the mod.

**Comment by MCPitman** [comment]
Without screenshots it's impossible to know what you are describing since I've never encountered it, I tried lightningcraft and did not see any obvious problems.

**Comment by LordSmellyPants** [comment]
Try using the latest version of OTG - OpenTerrainGenerator 1.11.2-v6
