### ISSUE TITLE
Half-generated jungle dungeon

### ISSUE THREAD

**Issue by AWConant** [BiomeBundle/BiomeBundle#77]
The world was generated on an Forge server running 1.11.2 - 13.20.0.2228. My client is patched with the same version, and I am running the most recent versions of OTG and BB. I came across a dungeon that seems to be half-generated. See the attached file. Inquire for the seed and coordinates if desired.

![3793b841c2f01d88e076a9593b87f1f0](https://user-images.githubusercontent.com/13953817/27458952-d11a82be-5779-11e7-8cb8-88c8e875aba9.jpg)

**Comment by MCPitman** [comment]
Seed and coords could be useful to see if it is reproducible.

Did you have any crashes or anything at any point, even non-OTG related ones? Just wondering if it could be that the game crashed during generation for whatever reason, leaving the building only partly generated.

**Comment by AWConant** [comment]
Seed: 1661687723771152027
X: 4925 Z: -3630

I'm afraid I don't remember if there were crashes. I'm trying to generate a single-player world with the same seed, but it's hanging at 'Loading world', so you might have to check it out yourself. I'll update this if my computer figures it out.

**Comment by MCPitman** [comment]
You probably don't have enough memory allocated to Minecraft. You need 2gb
or more.

**Comment by AWConant** [comment]
Good call. I did that in the past, but forgot to update my current profile for it.

**Comment by LordSmellyPants** [comment]
If you see any generation issues again after increasing memory please let us know :)

**Comment by AWConant** [comment]
Nope, it appears to be a gen issue. Just regenerated the world from the same seed in single player, and the dungeon appears as it does in the screenshot.

**Comment by MCPitman** [comment]
Fixed in BBundle v6
