### ISSUE TITLE
Biomes Bundle World Creation Broken? - Spigot

### ISSUE THREAD

**Issue by BiGUNMAN** [BiomeBundle/BiomeBundle#78]
Hi, I tried creating a world after dumping the "biomes bundle" assets data into their respective folders. Dumping the WorldBiomes into my test world WoldBiomes directory, and doing the same for the worldobjects, as well as overriding the default WorldConfig.ini. I did this for a test world called "otg".

I then proceeded to create the world (I'm using multiverse):
I used /mv create otg normal -g OpenTerrainGenerator
It posts an error.

Error:
http://i.imgur.com/vD17EVZ.png

I'm using this version of PaperSpigot:
http://i.imgur.com/g0WCQd5.png
- PaperSpigot is essentially the same as Spigot, so it shouldn't be the cause of the issue.

Anyways, hoping I could get some help.

**Comment by MCPitman** [comment]
The error above suggests you have another OTG/TC world that is using the same biome IDs as Biome Bundle. It seems to be the same issue as discussed here:

http://forum.mctcp.com/t/terraincontrol-issues/1630
