### ISSUE TITLE
Request - 1.10.2 Forge Biomes'O'Plenty support!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BiomeBundle/BiomeBundle#8]
I am considering using your mod but I am curious if you could add forge biomes'o'plenty support? If its not there that is. I love biomes 'o' plenty even back in 1.6.4 days. So I would greatly appreciate your consideration to my needs.

**Comment by BiomeBundle** [comment]
Unfortunately Terrain Control is not compatible with other mods that make changes to the overworld terrain. Until that changes we are unable to provide suppot for this

**Comment by P3rf3ctXZer0** [comment]
well make sure to let me know when you create support. I will eagerly await that day.
