### ISSUE TITLE
Water Level increase to Y=63?

### ISSUE THREAD

**Issue by SamGunGraven** [BiomeBundle/BiomeBundle#81]
Is there a possibility that this will be changed from the current Y=52 to the minecraft default Y=63, it would greatly increase mod compatibility?

**Comment by GirafiStudios** [comment]
Should be possible here: https://github.com/BiomeBundle/BiomeBundle/blob/BiomeBundleV5/Biome%20Bundle/WorldConfig.ini#L266

**Comment by SamGunGraven** [comment]
I've looked a little bit and there is also stuff in the 400+ .bc files like:
RiverWaterLevel: 52
WaterLevelMax: 52
Which is easy enough to change with some search and replace. 

Where it gets to be a chore is the MinHeight and MaxHeight for spawning in the BO3 files. It's not simply replaceable with a value of +11 since there are a number of caves etc as well. And there is 2565 files to be updated with new heights. Maybe first pass could just do a regular expression search and replace adding 11, but then you would have to know a lot to tune it afterwards.

**Comment by SamGunGraven** [comment]
I changed the water level to Y=63 in the world config, and then increased all water levels, height, minheight, maxheight, etc... in all .bc and .bo3 files by +11 and it seems to work reasonably well. But there are still some large areas of shallow water generating that should have been above water - I think it's due to negative biome height values dropping the blocks too low. If some of the maintainers sees this I'll gladly send my changed files to them. At least Savannah Edge and Steppe is encountering the problem of being submerged in water.

**Comment by SamGunGraven** [comment]
Further testing reveals almost all flat biomes to be under water. Most likely a combination of these factors
1. BiomeHeight (set in all .bc files) is set to negative in a lot of cases (described as BiomeHeight means how much height will be added in terrain generation, if this is based on the original height the numbers all need to be smaller by the difference between 52 and 63, probably adjusted manually for rounding as well)
2. CustomHeightControl (might also affect, and it's "may be found only experimentally")
3. RiverHeight negative and RiverCustomHeightControl might also be a culprit with overflowing rivers
I've attached my files if somebody wants to continue experimenting with increasing the level to Y=63
[Biome Bundle.zip](https://github.com/BiomeBundle/BiomeBundle/files/1153881/Biome.Bundle.zip)

**Comment by SamGunGraven** [comment]
Further testing shows that tweaking the BiomeHeight will get rid of the submerged in water problem. Challenge is that it's not very well documented (and nothing on the wiki either). I would like to have a mathematical formula to adjust the current settings. I don't think it's as simple as adding +0.14 or something. Anybody from either the Biome Bundle or OTG team that knows how Biome Height is calculated?

**Comment by SamGunGraven** [comment]
I have a working prototype now that has everything adjusted (except Dungeon, Plant, Liquid, Vines) and I've not touched the CustomHeightControl and RiverCustomHeightControl. But it looks pretty good already (keeping in mind that I don't have the same eye for terrain that the creators have). 

The big question now is, do you guys want this as a Pull Request? Or do you prefer me to create a public Fork of the project?

**Comment by SamGunGraven** [comment]
I ended up forking it - you may close if you don't want to merge those changes in

**Comment by MCPitman** [comment]
Done in v6
