### ISSUE TITLE
Biomes that theoretically can't spawn

### ISSUE THREAD

**Issue by SamGunGraven** [BiomeBundle/BiomeBundle#84]
The following Biomes is registred as a Custom Biome, but is not part of any biome group, isle biome or border biome - unless they are registrered as a river somewhere they should not theoretically spawn:
1. BirchForestTropical
2. CliffsSmall 
3. ForestCliffs 
4. ForestOakSmall
5. ForestPinyon
6. ForestPlateauPinyon
7. ForestPoplar
8. WebbedForest

**Comment by MCPitman** [comment]
Fixed in v6
