### ISSUE TITLE
Dungeons is missing from resource queue on 353 biome files

### ISSUE THREAD

**Issue by SamGunGraven** [BiomeBundle/BiomeBundle#85]
Only 98 biome files have Dungeon() set in their resource queue. This means dungeons are spawning a lot less than in vanilla

**Comment by LordSmellyPants** [comment]
We have bo3s that are like the vanilla dungeon but with different traps and styles to compliment the vanilla one. Hopefully will be bringing more structures and caves to the underground soon :)

**Comment by SamGunGraven** [comment]
It doesn't seem consistent though. Example is Dungeon being set on Alpine, but not AlpineConiferMountain where there is also an empty CustomStructure()

**Comment by MCPitman** [comment]
Fixed in v6
