### ISSUE TITLE
[Question] Install your mod on an existing server

### ISSUE THREAD

**Issue by ExDomino** [BiomeBundle/BiomeBundle#86]
Hello, we have an existing server and we plan to install your mod in order to create a new world (using Sponge) that use your terrain generator. I saw that in singleplayer, your mod modify the way that a world is created and on our server, we want that only one dimension, a new one created by a Sponge's plugin, uses your terrain generator. All other dimensions that already exist should not be affected. We have BiomesOPlenty but BOP has its own dimension as well. It is possible to install your mod as simple terrain modifier in our server? And what is the name of the terrain generator that we have to use in server.properties? For example, for BOP it's BIOMESOP. Will other mechanicals, like Enderman can only spawn in some biome, affect other dimension or only the one where your mod is set? Thanks you in advance!

**Comment by MCPitman** [comment]
This is an issue tracker, not a forum. Please post your question over at www.reddit.com/r/biomebundle
