### ISSUE TITLE
GitHub source different than v5.1 distributed version

### ISSUE THREAD

**Issue by SamGunGraven** [BiomeBundle/BiomeBundle#87]
In the Github files Deep Ocean has Ocean Monuments enabled, while if you download off CurseForge and open the JAR, the Deep Ocean biome has them disabled. I have not checked if there is other discrepancies as well.

**Comment by BiomeBundle** [comment]
1.10.2 and 1.11.2 are now available on Github - the master has been updated to the 1.11.2 version. Links to the Forge jar can be found on the sidebar of the [wiki](https://github.com/BiomeBundle/BiomeBundle/wiki)
