### ISSUE TITLE
Spigot 1.11.2 Invalid plugin.yml

### ISSUE THREAD

**Issue by bluewavess** [BiomeBundle/BiomeBundle#89]
Hello,
I am trying to run BiomeBundle with OTG on my Spigot 1.11.2 server.
The error it gives me is that the .jar does not contain a plugin.yml.
Any help?

https://gyazo.com/6808be64cbfe16f88891a6d767498ed5 <- Error that BiomeBundle gives me

Thanks in advance!

**Comment by MCPitman** [comment]
Please follow the wiki instructions for Spigot here:

http://openterraingen.wikia.com/wiki/Installing_Worlds
