### ISSUE TITLE
Botania Crash [1.10.2]

### ISSUE THREAD

**Issue by cvbn2000** [BiomeBundle/BiomeBundle#9]
Tried disabling Botania world gen, doesn't change the crash.
[crash-2017-01-02_20.07.17-server.txt](https://github.com/BiomeBundle/BiomeBundle/files/681569/crash-2017-01-02_20.07.17-server.txt)

**Comment by MCPitman** [comment]
Tried to recreate the crash with just Botania and Biome Bundle on default settings but cannot. Does it happen every time a new world is created?

**Comment by cvbn2000** [comment]
The only settings changed were:
[WorldConfig.txt](https://github.com/BiomeBundle/BiomeBundle/files/682602/WorldConfig.txt)
(Changed to .txt file for Upload)
# The size of the village. Larger is bigger. Normal worlds have 0 as default, superflat worlds 1.
VillageSize: 0
to
# The size of the village. Larger is bigger. Normal worlds have 0 as default, superflat worlds 1.
VillageSize: 1

and

# Set this to OBSIDIAN for "frozen" lava lakes in cold biomes
CooledLavaBlock: STATIONARY_LAVA 
to
# Set this to OBSIDIAN for "frozen" lava lakes in cold biomes
CooledLavaBlock: OBSIDIAN 

Here were the Mods I was using
http://www.modlister.com/user/Little_Pip

**Comment by BiomeBundle** [comment]
As you have so many mods installed it's impossible to figure out what could be causing the crash, the error log is not necessarily accurate.

As far as I can tell Biome Bundle and Botania together are not cause the issue.

**Comment by cvbn2000** [comment]
Got it narrowed down to these ![mods](https://cloud.githubusercontent.com/assets/17594615/21655456/1f520654-d288-11e6-9a25-c89b49347ec7.PNG), You were correct about it not being a Botania thing.

**Comment by MCPitman** [comment]
So I assume you get a different error in the log now?
