### ISSUE TITLE
BiomeBundle not working on latest TerrainControl 1.12

### ISSUE THREAD

**Issue by Probdutch** [BiomeBundle/BiomeBundle#90]
I have to use TerrainControl, as thats the only generator availible for spigot 1.12.

On starting i get these errors: https://hastebin.com/muneyucati.vbs

The generation works, but some objects aren't generating,

I would really like to see this fixed, as currently OpenTerrainGenerator has errors on startup with 1.12.
Thanks!

**Comment by MCPitman** [comment]
Terrain Control is no longer supported by Biome Bundle as it uses features which it does not have and TC is not very actively developed and has many bugs and problems.

The only solution here is to wait until OTG updates to 1.12.
