### ISSUE TITLE
List or guide about structures?

### ISSUE THREAD

**Issue by Nodws** [BiomeBundle/BiomeBundle#93]
Where can we find a guide/wiki about structures and loot tables (or what blocks of gold, diamonds, chests, etc it generates on each one)

Checked the reddit but they have no idea

**Comment by MCPitman** [comment]
It doesn't exist. I don't have time to document everything in biome bundle
it would take too much time.

It would have made more sense to wait for a reply on the subreddit, this is
an issue tracker not a Q&A forum. You didn't wait even 10 minutes for a
reply before posting here.

Closing this as it does not belong here.
