### ISSUE TITLE
Map doesn't generate fully?

### ISSUE THREAD

**Issue by Barryplayz** [BiomeBundle/BiomeBundle#95]
I've seen logdotzip's video about the biome bundle and downloaded his map because i run a 1.12 server and cant downgrade. Then when I downloaded the map i flied over it with a high flyspeed and i got at the end of the map?? After a while the maps seems to stop generating and the normal minecraft generation just goes on but a couple of blocks above the biom bundle generation. And because the normal minecraft generation isnt at the same height as the biome bundle generation it makes this weir looking walls of stone. Is this normal or is it a bug of some kind?

**Comment by MCPitman** [comment]
Why would the terrain continue generating biome bundle if you downloaded a map and did not install the mod properly?
